# General Settings
name: Andrzej Śliwa
job_title: Holistic CTO/VP Engineering, Polyglot Developer
email: andrzej.sliwa@i-tool.eu
description: I'm leading Engineering Team. I'm addicted to travelling and hiking at any given (and non-given) moment, getting into philosophical debates, and building the things. I'm coding since when software was stored on 5'25 floppies. Follow me on Twitter or drop me a line.
avatar: /assets/images/avatar.png
favicon: /favicon.ico
twitter_handler: andrzejsliwa
analytics_code:
disqus: andrzejsliwa

# Social Accounts
social_networks:
-  { name: twitter, url: 'http://twitter.com/andrzejsliwa' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/sliwa' }
-  { name: skype, url: 'andrzej.sliwa' }
-  { name: github, url: 'https://github.com/andrzejsliwa' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

