# General Settings
name: Andrzej Śliwa
job_title: Software Ninja
email: youremail@gmail.com
description: Entrepreneurship & startup samurai. Engineering team sensei. Black belt in problem solving.
avatar: /assets/images/avatar.jpg
favicon: /favicon.ico
twitter_handler: andrzejsliwa
analytics_code: UA-7007499-1
disqus: andrzejsliwa
baseurl: https://andrzejsliwa.com

# Social Accounts
social_networks:

-  { name: twitter, url: 'http://twitter.com/andrzejsliwa' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/sliwa' }
-  { name: skype, url: 'skype:andrzej.sliwa?call' }
-  { name: github, url: 'https://github.com/andrzejsliwa' }

# Modules Settings
show_categories: 1
show_tags: 1
show_mood: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
